import * as React from "react";
import Svg, {
  Defs,
  G,
  LinearGradient,
  Stop,
  Image,
  Rect,
  Text,
} from "react-native-svg";
/* SVGR has dropped some elements not supported by react-native-svg: d:SVGTestCase, title, fontFace, filter */
const SvgFiltersConv04F = (props) => (
  <Svg
    id="svg-root"
    width="100%"
    height="100%"
    viewBox="0 0 480 360"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    {...props}
  >
    <Defs></Defs>
    <G
      id="test-body-content"
      fontFamily="SVGFreeSansASCII,sans-serif"
      fontSize={18}
    >
      <Defs>
        <LinearGradient
          id="test_linear_gradient"
          gradientUnits="objectBoundingBox"
          x1={0}
          x2={1}
          y1={0}
          y2={0}
        >
          <Stop stopColor="#00FF00" stopOpacity={1} offset={0} />
          <Stop stopColor="#00FF00" stopOpacity={0} offset={1} />
        </LinearGradient>
      </Defs>
      <G transform="translate(0, 20)">
        <Image
          x={12}
          y={1}
          width={97}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={127}
          y={1}
          width={97}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={242}
          y={1}
          width={97}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={357}
          y={1}
          width={97}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={10}
          y={0}
          width={100}
          height={100}
          xlinkHref="../images/townsville.jpg"
        />
        <Image
          x={125}
          y={0}
          width={100}
          height={100}
          xlinkHref="../images/townsville.jpg"
          filter="url(#convolve-without-bias)"
        />
        <Image
          x={240}
          y={0}
          width={100}
          height={100}
          xlinkHref="../images/townsville.jpg"
          filter="url(#convolve-with-bias05)"
        />
        <Image
          x={355}
          y={0}
          width={100}
          height={100}
          xlinkHref="../images/townsville.jpg"
          filter="url(#convolve-with-bias1)"
        />
      </G>
      <G transform="translate(0, 110)">
        <Image
          x={11}
          y={51}
          width={98}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={126}
          y={51}
          width={98}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={241}
          y={51}
          width={98}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Image
          x={356}
          y={51}
          width={98}
          height={98}
          xlinkHref="../images/DisplaceChecker.png"
        />
        <Rect
          fill="url(#test_linear_gradient)"
          stroke="black"
          x={10}
          y={50}
          width={100}
          height={100}
        />
        <Rect
          fill="url(#test_linear_gradient)"
          stroke="black"
          x={125}
          y={50}
          width={100}
          height={100}
          filter="url(#convolve-without-bias)"
        />
        <Rect
          fill="url(#test_linear_gradient)"
          stroke="black"
          x={240}
          y={50}
          width={100}
          height={100}
          filter="url(#convolve-with-bias05)"
        />
        <Rect
          fill="url(#test_linear_gradient)"
          stroke="black"
          x={355}
          y={50}
          width={100}
          height={100}
          filter="url(#convolve-with-bias1)"
        />
      </G>
    </G>
    <G fontFamily="SVGFreeSansASCII,sans-serif" fontSize={32}>
      <Text id="revision" x={10} y={340} stroke="none" fill="black">
        {"$Revision: 1.4 $"}
      </Text>
    </G>
    <Rect
      id="test-frame"
      x={1}
      y={1}
      width={478}
      height={358}
      fill="none"
      stroke="#000"
    />
    <G id="draft-watermark">
      <Rect
        x={1}
        y={1}
        width={478}
        height={20}
        fill="red"
        stroke="black"
        strokeWidth={1}
      />
      <Text
        fontFamily="SVGFreeSansASCII,sans-serif"
        fontWeight="bold"
        fontSize={20}
        x={240}
        textAnchor="middle"
        y={18}
        strokeWidth={0.5}
        stroke="black"
        fill="white"
      >
        {"DRAFT"}
      </Text>
    </G>
  </Svg>
);
export default SvgFiltersConv04F;
