import * as React from "react";
import Svg, { Defs, G, Rect, Text } from "react-native-svg";
/* SVGR has dropped some elements not supported by react-native-svg: d:SVGTestCase, title, fontFace */
const SvgPaintingFill05B = (props) => (
  <Svg
    baseProfile="tiny"
    id="svg-root"
    width="100%"
    height="100%"
    viewBox="0 0 480 360"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    {...props}
  >
    <Defs></Defs>
    <G
      id="test-body-content"
      fontFamily="SVGFreeSansASCII,sans-serif"
      fontSize={18}
    >
      <Rect
        x={20}
        y={20}
        width={60}
        height={60}
        fillOpacity={0}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={50}
        y={50}
        width={60}
        height={60}
        fillOpacity={0.2}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={80}
        y={80}
        width={60}
        height={60}
        fillOpacity={0.4}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={110}
        y={110}
        width={60}
        height={60}
        fillOpacity={0.6}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={140}
        y={140}
        width={60}
        height={60}
        fillOpacity={0.8}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={170}
        y={170}
        width={60}
        height={60}
        fillOpacity={1}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={200}
        y={20}
        width={60}
        height={60}
        fillOpacity={-100}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={230}
        y={50}
        width={60}
        height={60}
        fillOpacity={-10}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={260}
        y={80}
        width={60}
        height={60}
        fillOpacity={-0.1}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={290}
        y={110}
        width={60}
        height={60}
        fillOpacity={1.1}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={320}
        y={140}
        width={60}
        height={60}
        fillOpacity={10}
        fill="#0000FF"
        stroke="black"
      />
      <Rect
        x={350}
        y={170}
        width={60}
        height={60}
        fillOpacity={100}
        fill="#0000FF"
        stroke="black"
      />
    </G>
    <G fontFamily="SVGFreeSansASCII,sans-serif" fontSize={32}>
      <Text id="revision" x={10} y={340} stroke="none" fill="black">
        {"$Revision: 1.5 $"}
      </Text>
    </G>
    <Rect
      id="test-frame"
      x={1}
      y={1}
      width={478}
      height={358}
      fill="none"
      stroke="#000000"
    />
  </Svg>
);
export default SvgPaintingFill05B;
