import * as React from "react";
import Svg, { Defs, G, Rect, Text } from "react-native-svg";
/* SVGR has dropped some elements not supported by react-native-svg: d:SVGTestCase, title, fontFace */
const SvgShapesRect01T = (props) => (
  <Svg
    baseProfile="tiny"
    id="svg-root"
    width="100%"
    height="100%"
    viewBox="0 0 480 360"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    {...props}
  >
    <Defs></Defs>
    <G
      id="test-body-content"
      fontFamily="SVGFreeSansASCII,sans-serif"
      fontSize={18}
    >
      <Rect
        id="Simple-rect-no-fill"
        fill="none"
        stroke="#000000"
        x={30}
        y={46}
        width={50}
        height={80}
      />
      <Rect
        id="Simple-rect-filled"
        fill="fuchsia"
        x={130}
        y={46}
        width={50}
        height={80}
      />
      <Rect
        id="Simple-round-rect-no-fill"
        fill="none"
        stroke="#000000"
        x={250}
        y={46}
        width={50}
        height={80}
        rx={30}
      />
      <Rect
        id="Simple-round-rect-filled"
        fill="fuchsia"
        x={350}
        y={46}
        width={50}
        height={80}
        rx={30}
      />
      <Rect
        id="rect-03"
        fill="none"
        stroke="#0000FF"
        strokeWidth={8}
        x={30}
        y={196}
        width={50}
        height={80}
      />
      <Rect
        id="rect-04"
        fill="#00FF00"
        stroke="#0000FF"
        strokeWidth={8}
        x={130}
        y={196}
        width={50}
        height={80}
      />
      <Rect
        id="rect-05"
        fill="none"
        stroke="#0000FF"
        strokeWidth={8}
        x={250}
        y={196}
        width={50}
        height={80}
        rx={30}
        ry={50}
      />
      <Rect
        id="rect-06"
        fill="#00FF00"
        x={350}
        y={196}
        width={50}
        height={80}
        rx={30}
        ry={50}
      />
    </G>
    <G fontFamily="SVGFreeSansASCII,sans-serif" fontSize={32}>
      <Text id="revision" x={10} y={340} stroke="none" fill="black">
        {"$Revision: 1.7 $"}
      </Text>
    </G>
    <Rect
      id="test-frame"
      x={1}
      y={1}
      width={478}
      height={358}
      fill="none"
      stroke="#000000"
    />
  </Svg>
);
export default SvgShapesRect01T;
